name: AI4Trade Auto Scraper

on:
  schedule:
    # 10:50 UTC = 17:50 WIB
    # 14:50 UTC = 21:50 WIB
    # 18:50 UTC = 01:50 WIB (Besok)
    # 22:50 UTC = 05:50 WIB (Besok)
    # 02:50 UTC = 09:50 WIB (Besok)
    # 06:50 UTC = 13:50 WIB (Besok)
    - cron: '57 2,6,10,14,16,22 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Discus Scraper
        env:
          G_SHEETS_CREDS: ${{ secrets.G_SHEETS_CREDS }}
        run: python discus.py

      - name: Run Strategies Scraper
        env:
          G_SHEETS_CREDS: ${{ secrets.G_SHEETS_CREDS }}
        run: python strategies.py
