name: AI4Trade Auto Scraper

on:
  schedule:
    # Menit 50, Jam 23, 3, 7, 11, 15, 19 UTC
    # Ini akan jalan jam 06:50, 10:50, 14:50, 18:50, 22:50, 02:50 WIB
    - cron: '50 3,7,11,15,19,23 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Discus Scraper
        env:
          G_SHEETS_CREDS: ${{ secrets.G_SHEETS_CREDS }}
        run: python discus.py

      - name: Run Strategies Scraper
        env:
          G_SHEETS_CREDS: ${{ secrets.G_SHEETS_CREDS }}
        run: python strategies.py
